type Props = {
  className?: string;
};

export default function AIBadge({ className = "" }: Props) {
  return (
    <span
      aria-label="Generated by AI"
      className={`ai-badge${className ? ` ${className}` : ""}`}
      title="Generado por Salon Intelligence"
    >
      AI
    </span>
  );
}
